name: Meetha Tales CI

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run automated tests
        run: python -m unittest discover -s tests

      - name: Build Docker image
        run: docker build -t meetha-tales .